"""Added is_admin column in users table

Revision ID: 76d74aac0a0d
Revises: f851fdac9280
Create Date: 2025-10-14 21:58:31.148700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76d74aac0a0d'
down_revision = 'f851fdac9280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_admin', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
