"""Added DispenseLog model and table

Revision ID: bdbb71335b92
Revises: 76d74aac0a0d
Create Date: 2025-10-17 12:55:20.350924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdbb71335b92'
down_revision = '76d74aac0a0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispense_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('litres_dispensed', sa.Float(), nullable=False),
    sa.Column('tokens_consumed', sa.Float(), nullable=False),
    sa.Column('machine_id', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dispense_logs')
    # ### end Alembic commands ###
