"""Added WaterUsage model and updated User Model for usage tracking

Revision ID: f851fdac9280
Revises: f62bb86d93ab
Create Date: 2025-10-11 22:22:16.482671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f851fdac9280'
down_revision = 'f62bb86d93ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('water_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('litres_dispensed', sa.Float(), nullable=False),
    sa.Column('tokens_used', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('water_usage')
    # ### end Alembic commands ###
